In [16]:
import pickle
import numpy as np
from os import listdir
import matplotlib.pyplot as plt
from scipy import stats
import math

In [17]:
# Load the data from results*.pkl
batchedResults = []
for filename in listdir('results'):
    if filename.startswith('results'):
        with open('results/' + filename, 'rb') as f:
            batchedResults.append(pickle.load(f))

In [18]:
# Extract the results
# ha_results = []
a_opts = []
errs = []
for batch in batchedResults:
    for result in batch:
        _, _, _, ha_result, _, _, err = result
        # ha_results.append(ha_result)
        a_opts.append(np.array(ha_result.x))
        errs.append(np.array(err))

In [19]:
# Prepare the data for plotting
a_opts = np.array(a_opts)
errs = np.concatenate(errs)
a_opts.shape, errs.shape

((2368, 3), (109222, 150))

In [20]:
a_opts[10]

array([ 1.01123753e-02,  3.89962935e-02, -3.97209241e+01])

In [21]:
# MSE
mse = np.mean(errs**2)
mse

0.04397864991804681

In [24]:
# Calculate stats for each parameter
# confidence level
cl = 0.95

n = a_opts.shape[0]
c, v, lamb = a_opts[:, 0], a_opts[:, 1], a_opts[:, 2]
t = stats.t.ppf((1 + cl) / 2, n - 1)
cstd = stats.tstd(c)
vstd = stats.tstd(v)
lstd = stats.tstd(lamb)
std = np.array([cstd, vstd, lstd])
moe = t * std / math.sqrt(n)
moe

array([3.01979349e-04, 1.80376250e-01, 5.41221825e-01])

In [23]:
np.mean(a_opts, axis=0)

array([ 0.00845944,  1.52615056, -1.52910777])